// frontend/src/components/DocumentEditor.tsx
import { useState, useEffect, useCallback } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Save, Trash2 } from 'lucide-react'
import type { Document } from '@/types'

interface DocumentEditorProps {
  documentId: number
}

export function DocumentEditor({ documentId }: DocumentEditorProps) {
  const [document, setDocument] = useState<Document | null>(null)
  const [title, setTitle] = useState('')
  const [content, setContent] = useState('')
  const [isSaving, setIsSaving] = useState(false)
  const [lastSaved, setLastSaved] = useState<Date | null>(null)

  useEffect(() => {
    const loadDocument = async () => {
      try {
        const response = await fetch(`/api/documents/${documentId}`, {
          credentials: 'include'
        })
        if (response.ok) {
          const doc = await response.json()
          setDocument(doc)
          setTitle(doc.title)
          setContent(doc.content)
        }
      } catch (error) {
        console.error('Failed to load document:', error)
      }
    }
    
    loadDocument()
  }, [documentId])

  const saveDocument = useCallback(async () => {
    if (!document) return

    setIsSaving(true)
    try {
      const response = await fetch(`/api/documents/${documentId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: title || 'Untitled',
          content
        }),
        credentials: 'include'
      })

      if (response.ok) {
        setLastSaved(new Date())
        // Trigger document list refresh
        window.dispatchEvent(new CustomEvent('document-updated'))
      }
    } catch (error) {
      console.error('Failed to save document:', error)
    } finally {
      setIsSaving(false)
    }
  }, [document, documentId, title, content])

  const deleteDocument = useCallback(async () => {
    if (!document) return

    const confirmed = window.confirm('Are you sure you want to delete this document?')
    if (!confirmed) return

    try {
      const response = await fetch(`/api/documents/${documentId}`, {
        method: 'DELETE',
        credentials: 'include'
      })

      if (response.ok) {
        // Trigger document deletion event
        window.dispatchEvent(new CustomEvent('document-deleted', {
          detail: { documentId }
        }))
      }
    } catch (error) {
      console.error('Failed to delete document:', error)
    }
  }, [document, documentId])

  // Auto-save functionality
  useEffect(() => {
    const timer = setTimeout(() => {
      if (document && (title !== document.title || content !== document.content)) {
        saveDocument()
      }
    }, 1000)

    return () => clearTimeout(timer)
  }, [title, content, document, saveDocument])

  if (!document) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-gray-500">Loading...</div>
      </div>
    )
  }

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="border-b border-gray-200 p-4">
        <div className="flex items-center justify-between">
          <Input
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Untitled"
            className="text-2xl font-bold border-none p-0 h-auto bg-transparent focus-visible:ring-0 focus-visible:ring-offset-0"
          />
          
          <div className="flex items-center space-x-2">
            {lastSaved && (
              <span className="text-sm text-gray-500">
                Saved {lastSaved.toLocaleTimeString()}
              </span>
            )}
            
            <Button
              onClick={saveDocument}
              disabled={isSaving}
              variant="outline"
              size="sm"
            >
              <Save className="h-4 w-4 mr-2" />
              {isSaving ? 'Saving...' : 'Save'}
            </Button>

            <Button
              onClick={deleteDocument}
              variant="outline"
              size="sm"
              className="text-red-600 hover:text-red-700 hover:bg-red-50"
            >
              <Trash2 className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>

      {/* Editor */}
      <div className="flex-1 p-4">
        <textarea
          value={content}
          onChange={(e) => setContent(e.target.value)}
          placeholder="Start writing..."
          className="w-full h-full border-none resize-none focus:outline-none text-base leading-relaxed"
        />
      </div>
    </div>
  )
}

// frontend/src/components/DocumentEditor.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import BlockEditor from './BlockEditor.svelte';
  
  let { documentId }: { documentId: number } = $props();
  
  interface Block {
    id: number;
    type: 'text' | 'heading' | 'checklist';
    content: any;
    position: number;
  }
  
  interface Document {
    id: number;
    title: string;
    content: string;
    blocks: Block[];
  }
  
  let document = $state<Document>({
    id: 0,
    title: '',
    content: '',
    blocks: []
  });
  
  let isLoading = $state(true);
  let saveTimeout: NodeJS.Timeout;
  let titleElement: HTMLElement;
  
  $effect(() => {
    if (documentId) {
      loadDocument();
    }
  });
  
  onDestroy(() => {
    if (saveTimeout) clearTimeout(saveTimeout);
  });
  
  async function loadDocument() {
    isLoading = true;
    try {
      const response = await fetch(`/api/documents/${documentId}`, {
        credentials: 'include'
      });
      
      if (response.ok) {
        document = await response.json();
      }
    } catch (error) {
      console.error('Failed to load document:', error);
    } finally {
      isLoading = false;
    }
  }
  
  function debouncedSave() {
    if (saveTimeout) clearTimeout(saveTimeout);
    saveTimeout = setTimeout(saveDocument, 2000);
  }
  
  async function saveDocument() {
    try {
      await fetch(`/api/documents/${document.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          title: document.title,
          blocks: document.blocks
        })
      });
    } catch (error) {
      console.error('Failed to save document:', error);
    }
  }
  
  function onTitleChange() {
    debouncedSave();
  }
  
  function addBlock(type: Block['type'], afterIndex?: number) {
    const newBlock: Block = {
      id: Date.now(),
      type,
      content: getDefaultContent(type),
      position: afterIndex !== undefined ? afterIndex + 1 : document.blocks.length
    };
    
    if (afterIndex !== undefined) {
      document.blocks.splice(afterIndex + 1, 0, newBlock);
      // 後続ブロックのposition更新
      for (let i = afterIndex + 2; i < document.blocks.length; i++) {
        document.blocks[i].position = i;
      }
    } else {
      document.blocks = [...document.blocks, newBlock];
    }
    
    debouncedSave();
    
    // 新しいブロックにフォーカス
    setTimeout(() => {
      const newBlockElement = window.document.querySelector(`[data-block-id="${newBlock.id}"]`);
      if (newBlockElement) {
        (newBlockElement as HTMLElement).focus();
      }
    }, 50);
  }
  
  function getDefaultContent(type: Block['type']) {
    switch (type) {
      case 'text':
        return { text: '' };
      case 'heading':
        return { text: '', level: 1 };
      case 'checklist':
        return { items: [{ text: '', checked: false }] };
      default:
        return { text: '' };
    }
  }
  
  function deleteBlock(blockId: number) {
    const index = document.blocks.findIndex(b => b.id === blockId);
    if (index > -1) {
      document.blocks.splice(index, 1);
      // 後続ブロックのposition更新
      for (let i = index; i < document.blocks.length; i++) {
        document.blocks[i].position = i;
      }
      debouncedSave();
    }
  }
  
  function moveBlock(blockId: number, direction: 'up' | 'down') {
    const index = document.blocks.findIndex(b => b.id === blockId);
    if (index === -1) return;
    
    const newIndex = direction === 'up' ? index - 1 : index + 1;
    if (newIndex < 0 || newIndex >= document.blocks.length) return;
    
    // ブロックを交換
    [document.blocks[index], document.blocks[newIndex]] = [document.blocks[newIndex], document.blocks[index]];
    
    // position更新
    document.blocks[index].position = index;
    document.blocks[newIndex].position = newIndex;
    
    document.blocks = [...document.blocks];
    debouncedSave();
  }
  
  function onBlockContentChange(blockId: number, newContent: any) {
    const block = document.blocks.find(b => b.id === blockId);
    if (block) {
      block.content = newContent;
      debouncedSave();
    }
  }
  
  // キーボードショートカット
  function handleKeydown(event: KeyboardEvent) {
    if (event.key === '/' && event.target === titleElement) {
      event.preventDefault();
      addBlock('text');
    }
  }
</script>

<div class="h-full overflow-y-auto" onkeydown={handleKeydown}>
  {#if isLoading}
    <div class="flex items-center justify-center h-full">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
    </div>
  {:else}
    <div class="max-w-4xl mx-auto p-8">
      <!-- タイトル -->
      <input 
        bind:this={titleElement}
        bind:value={document.title}
        oninput={onTitleChange}
        placeholder="Untitled"
        class="w-full text-4xl font-bold border-none outline-none mb-8 placeholder-gray-400"
      />
      
      <!-- ブロックエディタ -->
      <div class="space-y-1">
        {#each document.blocks as block, index (block.id)}
          <BlockEditor 
            {block}
            onContentChange={(content) => onBlockContentChange(block.id, content)}
            onAddBlock={(type) => addBlock(type, index)}
            onDeleteBlock={() => deleteBlock(block.id)}
            onMoveUp={() => moveBlock(block.id, 'up')}
            onMoveDown={() => moveBlock(block.id, 'down')}
            canMoveUp={index > 0}
            canMoveDown={index < document.blocks.length - 1}
          />
        {/each}
      </div>
      
      <!-- 新しいブロック追加 -->
      {#if document.blocks.length === 0}
        <div class="mt-4">
          <button 
            onclick={() => addBlock('text')}
            class="flex items-center text-gray-500 hover:text-gray-700 p-2 rounded hover:bg-gray-50"
          >
            <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
            </svg>
            Click to add your first block
          </button>
        </div>
      {/if}
    </div>
  {/if}
</div>
