// frontend-svelte/src/lib/components/ReadOnlyDocumentViewer.svelte
<script lang="ts">
  import Input from "$lib/components/ui/input.svelte";
  import ReadOnlyRichTextViewer from "./ReadOnlyRichTextViewer.svelte";
  import type {
    ReadOnlyDocumentViewerProps,
    Block,
    ImageBlockContent,
    FileBlockContent,
  } from "$lib/types";
  import { createReadOnlyDocumentViewerStore } from "$lib/stores/useReadOnlyDocumentViewer.svelte";
  import {
    Download,
    File,
    FileText,
    FileSpreadsheet,
    FileCode,
    FileArchive,
  } from "lucide-svelte";
  import {
    getFileIconName,
    formatFileSize,
    getFileTypeName,
  } from "$lib/utils/fileUploadUtils";

  /**
   * 読み取り専用ドキュメントビューアーコンポーネント
   * ゴミ箱内のドキュメントを読み取り専用で表示する
   *
   * 特徴:
   * - 全ての編集機能を無効化
   * - グレーアウト表示で読み取り専用であることを明示
   * - テキスト選択とコピーは可能
   */

  // Props
  let { documentId, onClose = undefined }: ReadOnlyDocumentViewerProps =
    $props();

  // ストアを作成
  let store = $state(createReadOnlyDocumentViewerStore(documentId));

  // documentIdが変更された場合、ストアを再作成
  $effect(() => {
    store = createReadOnlyDocumentViewerStore(documentId);
  });

  /**
   * ファイルアイコンを取得
   */
  function getFileIcon(mimeType: string) {
    const iconName = getFileIconName(mimeType);

    switch (iconName) {
      case "file-text":
        return FileText;
      case "file-spreadsheet":
        return FileSpreadsheet;
      case "file-code":
        return FileCode;
      case "file-archive":
        return FileArchive;
      default:
        return File;
    }
  }

  /**
   * 画像ブロックかどうかを判定
   */
  function isImageBlock(
    block: Block
  ): block is Block & { content: ImageBlockContent } {
    return block.type === "image" && typeof block.content === "object";
  }

  /**
   * ファイルブロックかどうかを判定
   */
  function isFileBlock(
    block: Block
  ): block is Block & { content: FileBlockContent } {
    return block.type === "file" && typeof block.content === "object";
  }

  /**
   * テキストブロックの内容を取得
   */
  function getTextContent(block: Block): string {
    if (typeof block.content === "string") {
      return block.content;
    }
    return "";
  }
</script>

<div class="h-full overflow-auto">
  <!-- ローディング状態 -->
  {#if store.isLoading}
    <div class="flex items-center justify-center h-full">
      <div class="text-gray-500">Loading...</div>
    </div>
    <!-- エラー状態 -->
  {:else if store.error}
    <div class="flex items-center justify-center h-full">
      <div class="text-red-500">Error: {store.error}</div>
    </div>
    <!-- ドキュメント未検出 -->
  {:else if !store.document}
    <div class="flex items-center justify-center h-full">
      <div class="text-gray-500">Document not found</div>
    </div>
    <!-- ドキュメント表示 -->
  {:else}
    <!-- 読み取り専用コンテナ（全体を70%透明化、クリック無効） -->
    <div class="opacity-70 pointer-events-none">
      <!-- バナー -->
      <div
        class="bg-gray-100 border-b border-gray-200 px-4 py-2 flex items-center justify-center pointer-events-auto"
      >
        <span class="text-sm text-gray-600">
          📄 このドキュメントは読み取り専用です（ゴミ箱内）
        </span>
      </div>

      <div class="px-4 py-6 max-w-4xl mx-auto">
        <!-- タイトル入力欄（読み取り専用） -->
        <Input
          value={store.document.title}
          readonly
          tabindex={-1}
          class="text-2xl font-bold border-0 focus:ring-0 px-0 mb-4 pointer-events-none"
        />

        <!-- ブロックリスト -->
        <div class="space-y-2 pl-20">
          {#if store.document.blocks && store.document.blocks.length > 0}
            {#each store.document.blocks as block (block.id)}
              <div class="group relative">
                <!-- テキストブロック -->
                {#if block.type === "text"}
                  <div class="min-h-[2rem] select-text pointer-events-auto">
                    <ReadOnlyRichTextViewer content={getTextContent(block)} />
                  </div>
                  <!-- 画像ブロック -->
                {:else if isImageBlock(block)}
                  {@const imageContent = block.content}
                  <div
                    class="my-4 select-text pointer-events-auto max-w-2xl mx-auto"
                  >
                    {#if imageContent.src}
                      <img
                        src={imageContent.src}
                        alt={imageContent.alt ||
                          imageContent.originalName ||
                          "Image"}
                        class="w-full h-auto rounded-lg shadow-md"
                        style={imageContent.width
                          ? `max-width: ${imageContent.width}px`
                          : ""}
                      />
                      {#if imageContent.caption}
                        <div class="text-center text-sm text-gray-600 mt-2">
                          {imageContent.caption}
                        </div>
                      {/if}
                    {:else}
                      <div
                        class="bg-gray-100 rounded-lg p-4 text-center text-gray-500"
                      >
                        画像が見つかりません
                      </div>
                    {/if}
                  </div>
                  <!-- ファイルブロック -->
                {:else if isFileBlock(block)}
                  {@const fileContent = block.content}
                  {@const FileIcon = getFileIcon(fileContent.mimeType)}
                  <div
                    class="my-4 border border-gray-200 rounded-lg p-4 bg-gray-50 max-w-xl"
                  >
                    <div class="flex items-start space-x-3">
                      <!-- ファイルアイコン -->
                      <div class="flex-shrink-0 mt-1">
                        <FileIcon class="w-8 h-8 text-gray-400" />
                      </div>

                      <!-- ファイル情報 -->
                      <div class="flex-1 min-w-0">
                        <div class="font-medium text-gray-900 truncate">
                          {fileContent.originalName || fileContent.filename}
                        </div>
                        <div class="text-sm text-gray-500 mt-1">
                          {getFileTypeName(fileContent.mimeType)} •
                          {formatFileSize(fileContent.fileSize)}
                        </div>
                        {#if fileContent.uploadedAt}
                          <div class="text-xs text-gray-400 mt-1">
                            アップロード日時: {new Date(
                              fileContent.uploadedAt
                            ).toLocaleString("ja-JP")}
                          </div>
                        {/if}
                      </div>

                      <!-- ダウンロードボタン -->
                      {#if fileContent.downloadUrl}
                        <a
                          href={fileContent.downloadUrl}
                          download={fileContent.originalName ||
                            fileContent.filename}
                          class="flex-shrink-0 p-2 hover:bg-gray-100 rounded-md transition-colors pointer-events-auto"
                          title="ダウンロード"
                        >
                          <Download class="w-5 h-5 text-gray-600" />
                        </a>
                      {/if}
                    </div>
                  </div>
                  <!-- その他のブロックタイプ -->
                {:else}
                  <div class="text-gray-400 italic">
                    Unknown block type: {block.type}
                  </div>
                {/if}
              </div>
            {/each}
          {:else}
            <div class="text-gray-400 italic py-4">
              このドキュメントにはコンテンツがありません
            </div>
          {/if}
        </div>
      </div>
    </div>
  {/if}
</div>

// frontend/src/components/ReadOnlyDocumentViewer.tsx
import { Input } from '@/components/ui/input'
import { ReadOnlyRichTextViewer } from './ReadOnlyRichTextViewer'
import type {
  ReadOnlyDocumentViewerProps,
  FileBlockContent,
  ImageBlockContent,
} from '@/types'
import { useReadOnlyDocumentViewer } from '@/hooks/useReadOnlyDocumentViewer'
import {
  Download,
  File,
  FileText,
  FileSpreadsheet,
  FileCode,
  FileArchive,
} from 'lucide-react'
import {
  getFileIconName,
  formatFileSize,
  getFileTypeName,
} from '@/utils/fileUploadUtils'

/**
 * 読み取り専用ドキュメントビューアーコンポーネント
 * ゴミ箱内のドキュメントを読み取り専用で表示する
 *
 * 特徴:
 * - 全ての編集機能を無効化
 * - グレーアウト表示で読み取り専用であることを明示
 * - テキスト選択とコピーは可能
 */
export function ReadOnlyDocumentViewer({
  documentId,
}: ReadOnlyDocumentViewerProps) {
  const { document, isLoading, error } = useReadOnlyDocumentViewer(documentId)

  // ローディング状態
  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-gray-500">Loading...</div>
      </div>
    )
  }

  // エラー状態
  if (error) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-red-500">Error: {error}</div>
      </div>
    )
  }

  // ドキュメントが見つからない場合
  if (!document) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-gray-500">Document not found</div>
      </div>
    )
  }

  return (
    <div className="flex flex-col h-full opacity-70 pointer-events-none select-text">
      {/* 読み取り専用であることを示すバナー */}
      <div className="bg-gray-100 border-b border-gray-200 px-4 py-2 pointer-events-auto">
        <div className="flex items-center justify-center">
          <span className="text-sm text-gray-600 font-medium">
            📄 このドキュメントは読み取り専用です（ゴミ箱内）
          </span>
        </div>
      </div>

      {/* ヘッダー - タイトル表示（読み取り専用） */}
      <div className="border-b border-gray-200 p-4 pointer-events-auto">
        <div className="flex items-center justify-between">
          <Input
            value={document.title || 'Untitled'}
            readOnly
            className="text-2xl font-bold border-none p-0 h-auto bg-transparent focus-visible:ring-0 focus-visible:ring-offset-0 cursor-default"
            data-testid="readonly-document-title"
            tabIndex={-1} // タブナビゲーションから除外
          />
        </div>
      </div>

      {/* コンテンツエリア - ブロック表示（読み取り専用） */}
      <div className="flex-1 p-4 pl-20 pointer-events-auto">
        <div className="max-w-4xl">
          {document.blocks && document.blocks.length > 0 ? (
            <div className="space-y-2">
              {document.blocks.map(block => (
                <div
                  key={`readonly-block-${block.id}`}
                  className="group relative"
                  data-testid={`readonly-block-${block.id}`}
                >
                  {/* ブロックコンテンツ */}
                  <div className="min-h-[2rem] p-2 rounded border border-transparent">
                    {block.type === 'image' ? (
                      /* 画像ブロックの読み取り専用表示 */
                      <ReadOnlyImageBlock
                        content={block.content as string | ImageBlockContent}
                      />
                    ) : block.type === 'file' ? (
                      /* ファイルブロックの読み取り専用表示 */
                      <ReadOnlyFileBlock
                        content={block.content as string | FileBlockContent}
                      />
                    ) : (
                      /* テキストブロックの読み取り専用表示 */
                      <div data-testid={`readonly-block-content-${block.id}`}>
                        <ReadOnlyRichTextViewer
                          content={
                            typeof block.content === 'string'
                              ? block.content
                              : ''
                          }
                        />
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            /* 空のドキュメント表示 */
            <div className="flex items-center justify-center h-32 text-gray-400">
              <span>このドキュメントには内容がありません</span>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

/**
 * 画像ブロックの読み取り専用表示コンポーネント
 */
function ReadOnlyImageBlock({
  content,
}: {
  content: string | ImageBlockContent
}) {
  try {
    // contentが既にオブジェクトの場合はそのまま使用
    const imageData =
      typeof content === 'string' ? JSON.parse(content) : content

    return (
      <div className="flex flex-col items-start space-y-2">
        <img
          src={imageData.src}
          alt={imageData.alt || ''}
          className="max-w-full h-auto rounded border border-gray-200"
          style={{
            width: imageData.width ? `${imageData.width}px` : 'auto',
            height: imageData.height ? `${imageData.height}px` : 'auto',
          }}
        />
        {imageData.caption && (
          <p className="text-sm text-gray-600 italic">{imageData.caption}</p>
        )}
      </div>
    )
  } catch {
    // JSON パースに失敗した場合は、プレーンテキストとして表示
    return (
      <div className="text-gray-500 italic">
        画像を表示できません: {String(content)}
      </div>
    )
  }
}

/**
 * ファイルブロックの読み取り専用表示コンポーネント
 */
function ReadOnlyFileBlock({
  content,
}: {
  content: string | FileBlockContent
}) {
  try {
    // contentが既にオブジェクトの場合はそのまま使用
    const fileData: FileBlockContent =
      typeof content === 'string' ? JSON.parse(content) : content

    // ファイルアイコンを取得
    const getFileIcon = (mimeType: string) => {
      const iconName = getFileIconName(mimeType)

      switch (iconName) {
        case 'FileText':
          return <FileText className="h-10 w-10" />
        case 'FileSpreadsheet':
          return <FileSpreadsheet className="h-10 w-10" />
        case 'FileCode':
          return <FileCode className="h-10 w-10" />
        case 'FileArchive':
          return <FileArchive className="h-10 w-10" />
        default:
          return <File className="h-10 w-10" />
      }
    }

    return (
      <div className="flex items-center space-x-4 rounded-lg border border-gray-200 bg-gray-50 p-4">
        {/* ファイルアイコン */}
        <div className="flex h-14 w-14 flex-shrink-0 items-center justify-center rounded-lg bg-blue-50 text-blue-500">
          {getFileIcon(fileData.mimeType)}
        </div>

        {/* ファイル詳細 */}
        <div className="min-w-0 flex-1">
          <h4 className="truncate text-sm font-medium text-gray-900">
            {fileData.originalName || fileData.filename}
          </h4>
          <div className="mt-1 flex items-center space-x-2 text-xs text-gray-500">
            <span className="rounded bg-gray-100 px-2 py-0.5 font-medium">
              {getFileTypeName(fileData.mimeType)}
            </span>
            {fileData.fileSize > 0 && (
              <span>• {formatFileSize(fileData.fileSize)}</span>
            )}
            {fileData.uploadedAt && (
              <span>
                • {new Date(fileData.uploadedAt).toLocaleDateString('ja-JP')}
              </span>
            )}
          </div>
        </div>

        {/* ダウンロードボタン */}
        <a
          href={fileData.downloadUrl}
          download={fileData.originalName || fileData.filename}
          target="_blank"
          rel="noopener noreferrer"
          className="flex flex-shrink-0 items-center space-x-2 rounded-md border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 pointer-events-auto"
        >
          <Download className="h-4 w-4" />
          <span>ダウンロード</span>
        </a>
      </div>
    )
  } catch {
    // JSON パースに失敗した場合は、プレーンテキストとして表示
    return (
      <div className="text-gray-500 italic">
        ファイルを表示できません: {String(content)}
      </div>
    )
  }
}
