// frontend-svelte/src/lib/components/RichTextEditor.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { Editor } from "@tiptap/core";
  import { Document } from "@tiptap/extension-document";
  import { Paragraph } from "@tiptap/extension-paragraph";
  import { Text } from "@tiptap/extension-text";
  import { Bold } from "@tiptap/extension-bold";
  import { Italic } from "@tiptap/extension-italic";
  import { Strike } from "@tiptap/extension-strike";
  import { Underline } from "@tiptap/extension-underline";
  import { Color } from "@tiptap/extension-color";
  import { Highlight } from "@tiptap/extension-highlight";
  import { TextStyle } from "@tiptap/extension-text-style";
  import { Link } from "@tiptap/extension-link";
  import { HardBreak } from "@tiptap/extension-hard-break";
  import { Dropcursor } from "@tiptap/extension-dropcursor";
  import { Gapcursor } from "@tiptap/extension-gapcursor";
  import Button from "$lib/components/ui/button.svelte";
  import {
    Bold as BoldIcon,
    Italic as ItalicIcon,
    Underline as UnderlineIcon,
    Strikethrough,
    Link as LinkIcon,
  } from "lucide-svelte";
  import {
    normalizeContent,
    getSelectionCoordinates,
    hasSelection,
  } from "$lib/utils/editorUtils";

  // Props
  let {
    content = $bindable(""),
    placeholder = "Start typing...",
    onUpdate = $bindable<(content: string) => void>(() => {}),
    onFocus = $bindable<() => void>(() => {}),
    onKeyDown = $bindable<
      ((event: KeyboardEvent) => boolean | void) | undefined
    >(undefined),
    class: className = "",
  } = $props();

  // State
  let editorElement: HTMLDivElement | null = $state(null);
  let editor: Editor | null = $state(null);
  let showToolbar = $state(false);
  let toolbarPosition = $state({ top: 0, left: 0 });
  let lastContent = $state("");
  let isUpdating = $state(false);

  /**
   * テキスト選択時のツールバー表示処理
   */
  function handleSelectionUpdate() {
    if (hasSelection() && editorElement) {
      const coords = getSelectionCoordinates(editorElement);
      if (coords) {
        toolbarPosition = coords;
        showToolbar = true;
      }
    } else {
      showToolbar = false;
    }
  }

  /**
   * エディター初期化
   */
  onMount(() => {
    if (!editorElement) return;

    editor = new Editor({
      element: editorElement,
      extensions: [
        Document,
        Paragraph.configure({
          HTMLAttributes: {
            class: "outline-none leading-normal my-1 min-h-[1.5rem]",
          },
        }),
        Text,
        TextStyle,
        Color.configure({
          types: ["textStyle"],
        }),
        Highlight.configure({
          multicolor: true,
        }),
        Link.configure({
          openOnClick: false,
          HTMLAttributes: {
            class:
              "text-blue-600 underline decoration-blue-600 hover:text-blue-700 cursor-pointer",
            rel: "noopener noreferrer",
          },
        }),
        Bold,
        Italic,
        Strike,
        HardBreak,
        Dropcursor,
        Gapcursor,
        Underline.configure({
          HTMLAttributes: {
            class:
              "underline decoration-2 underline-offset-2 decoration-blue-500",
          },
        }),
      ],
      content: normalizeContent(content || ""),
      autofocus: true,
      editable: true,
      onUpdate: ({ editor }: { editor: Editor }) => {
        if (isUpdating) return;

        try {
          const json = editor.getJSON();
          const jsonString = JSON.stringify(json);

          if (jsonString !== lastContent) {
            lastContent = jsonString;
            onUpdate(jsonString);
          }
        } catch (error) {
          console.debug("RichTextEditor update error:", error);
        }
      },
      onSelectionUpdate: () => {
        try {
          handleSelectionUpdate();
        } catch (error) {
          console.debug("RichTextEditor selection update error:", error);
        }
      },
      onFocus: () => {
        onFocus();
      },
      onBlur: () => {
        setTimeout(() => {
          showToolbar = false;
        }, 100);
      },
      editorProps: {
        attributes: {
          class:
            "prose prose-sm sm:prose-base max-w-none focus:outline-none min-h-[2rem] leading-normal",
          placeholder: placeholder,
          spellcheck: "false",
        },
        handleKeyDown: (_view: any, event: KeyboardEvent) => {
          if (onKeyDown) {
            const result = onKeyDown(event);
            if (result === false) {
              return true;
            }
          }
          return false;
        },
      },
    });

    return () => {
      if (editor) {
        editor.destroy();
      }
    };
  });

  /**
   * コンテンツ同期
   */
  $effect(() => {
    if (!editor || isUpdating) return;

    const currentContent = JSON.stringify(editor.getJSON());
    const incomingContent = content || "";

    if (incomingContent === lastContent || incomingContent === currentContent) {
      return;
    }

    if (editor.isFocused) {
      return;
    }

    isUpdating = true;
    try {
      const normalizedContent = normalizeContent(incomingContent);
      editor.commands.setContent(normalizedContent, { emitUpdate: false });
      lastContent = incomingContent;
    } catch (error) {
      console.debug("Content sync error:", error);
    } finally {
      setTimeout(() => {
        isUpdating = false;
      }, 50);
    }
  });

  /**
   * ツールバーアクション
   */
  function toggleBold() {
    editor?.chain().focus().toggleBold().run();
  }

  function toggleItalic() {
    editor?.chain().focus().toggleItalic().run();
  }

  function toggleUnderline() {
    editor?.chain().focus().toggleUnderline().run();
  }

  function toggleStrike() {
    editor?.chain().focus().toggleStrike().run();
  }

  function isFormatActive(format: string): boolean {
    return editor?.isActive(format) ?? false;
  }

  onDestroy(() => {
    if (editor) {
      editor.destroy();
    }
  });
</script>

<div class="relative">
  <!-- メインエディター -->
  <div bind:this={editorElement} class={`relative ${className}`}></div>

  <!-- フローティングツールバー -->
  {#if showToolbar}
    <div
      class="absolute z-10 bg-white border border-gray-200 rounded shadow-lg p-1 flex space-x-1"
      style:top={`${toolbarPosition.top}px`}
      style:left={`${toolbarPosition.left}px`}
      data-toolbar
    >
      <Button
        size="sm"
        variant={isFormatActive("bold") ? "default" : "ghost"}
        onclick={toggleBold}
        class="h-6 w-6 p-1"
      >
        <BoldIcon class="h-3 w-3" />
      </Button>
      <Button
        size="sm"
        variant={isFormatActive("italic") ? "default" : "ghost"}
        onclick={toggleItalic}
        class="h-6 w-6 p-1"
      >
        <ItalicIcon class="h-3 w-3" />
      </Button>
      <Button
        size="sm"
        variant={isFormatActive("underline") ? "default" : "ghost"}
        onclick={toggleUnderline}
        class="h-6 w-6 p-1"
      >
        <UnderlineIcon class="h-3 w-3" />
      </Button>
      <Button
        size="sm"
        variant={isFormatActive("strike") ? "default" : "ghost"}
        onclick={toggleStrike}
        class="h-6 w-6 p-1"
      >
        <Strikethrough class="h-3 w-3" />
      </Button>
    </div>
  {/if}
</div>

// frontend/src/components/RichTextEditor.tsx
import { useEditor, EditorContent } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import Underline from '@tiptap/extension-underline'
import { Button } from '@/components/ui/button'
import { Bold, Italic, Underline as UnderlineIcon, Strikethrough } from 'lucide-react'
import { useCallback, useEffect, useState, useRef } from 'react'
import type { KeyboardEvent as ReactKeyboardEvent } from 'react'

interface RichTextEditorProps {
  content: string
  placeholder?: string
  className?: string
  onUpdate: (content: string) => void
  onFocus?: () => void
  onKeyDown?: (event: ReactKeyboardEvent) => boolean | void
}

/**
 * Rich text editor component using TipTap
 * Supports bold, italic, underline, and strikethrough formatting
 */
export function RichTextEditor({
  content,
  placeholder = 'Start typing...',
  className = '',
  onUpdate,
  onFocus,
  onKeyDown
}: RichTextEditorProps) {
  const [showToolbar, setShowToolbar] = useState(false)
  const [toolbarPosition, setToolbarPosition] = useState({ top: 0, left: 0 })
  const editorRef = useRef<HTMLDivElement>(null)

  // Get selection coordinates for toolbar positioning
  const getSelectionCoordinates = useCallback(() => {
    const selection = window.getSelection()
    if (!selection || selection.rangeCount === 0) return null

    const range = selection.getRangeAt(0)
    const rect = range.getBoundingClientRect()
    const editorRect = editorRef.current?.getBoundingClientRect()
    
    if (!editorRect) return null

    // ツールバーの幅（約150px）を考慮した位置計算
    const toolbarWidth = 150
    const selectionCenter = rect.left - editorRect.left + (rect.width / 2)
    
    // 左端で見切れないように調整
    let left = selectionCenter - (toolbarWidth / 2)
    if (left < 10) {
      left = 10 // 最小マージン
    }
    
    // 右端で見切れないように調整
    const maxLeft = editorRect.width - toolbarWidth - 10
    if (left > maxLeft) {
      left = maxLeft
    }

    return {
      top: rect.top - editorRect.top - 50, // Position above selection
      left: left
    }
  }, [])

  const handleSelectionUpdate = useCallback(() => {
    const selection = window.getSelection()
    const hasSelection = selection && !selection.isCollapsed && selection.toString().trim().length > 0
    
    if (hasSelection) {
      const coords = getSelectionCoordinates()
      if (coords) {
        setToolbarPosition(coords)
        setShowToolbar(true)
      }
    } else {
      setShowToolbar(false)
    }
  }, [getSelectionCoordinates])
  
  const editor = useEditor({
    extensions: [
      StarterKit.configure({
        // Disable unused features to keep it lightweight
        heading: false,
        bulletList: false,
        orderedList: false,
        blockquote: false,
        codeBlock: false,
        horizontalRule: false,
        // Keep only paragraph and inline formatting
        paragraph: {
          HTMLAttributes: {
            class: 'outline-none'
          }
        }
      }),
      Underline
    ],
    content: content || '',
    onUpdate: ({ editor }) => {
      const json = editor.getJSON()
      onUpdate(JSON.stringify(json))
    },
    onSelectionUpdate: () => {
      // Use setTimeout to ensure DOM is updated
      setTimeout(handleSelectionUpdate, 0)
    },
    onFocus: () => {
      onFocus?.()
    },
    onBlur: ({ event }) => {
      // Check if the blur is caused by clicking on toolbar
      const relatedTarget = event.relatedTarget as HTMLElement
      if (relatedTarget && relatedTarget.closest('[data-toolbar]')) {
        return // Don't hide toolbar if clicking on toolbar buttons
      }
      setTimeout(() => setShowToolbar(false), 150)
    },
    editorProps: {
      attributes: {
        class: `prose prose-sm sm:prose lg:prose-lg xl:prose-2xl mx-auto focus:outline-none ${className}`,
        placeholder: placeholder
      },
      handleKeyDown: (_view, event) => {
        if (onKeyDown) {
          const result = onKeyDown(event as unknown as ReactKeyboardEvent)
          if (result === false) {
            return true // Prevent default
          }
        }
        return false // Allow default behavior
      }
    }
  })

  // Update editor content when prop changes
  useEffect(() => {
    if (editor && content !== JSON.stringify(editor.getJSON())) {
      try {
        if (content === '' || content === null || content === undefined) {
          // Handle empty content
          editor.commands.setContent({ type: 'doc', content: [] })
        } else if (content.trim().startsWith('{')) {
          // Try to parse as JSON (TipTap format)
          const parsedContent = JSON.parse(content)
          if (parsedContent.type === 'doc') {
            editor.commands.setContent(parsedContent)
          } else {
            // Invalid TipTap structure, treat as plain text
            editor.commands.setContent(`<p>${content}</p>`)
          }
        } else {
          // Plain text content, convert to paragraph
          editor.commands.setContent(`<p>${content}</p>`)
        }
      } catch (error) {
        // If JSON parsing fails, treat as plain text
        console.warn('Failed to parse rich text content, treating as plain text:', error)
        editor.commands.setContent(`<p>${content}</p>`)
      }
    }
  }, [content, editor])

  const toggleBold = useCallback(() => {
    editor?.chain().focus().toggleBold().run()
  }, [editor])

  const toggleItalic = useCallback(() => {
    editor?.chain().focus().toggleItalic().run()
  }, [editor])

  const toggleUnderline = useCallback(() => {
    editor?.chain().focus().toggleUnderline().run()
  }, [editor])

  const toggleStrike = useCallback(() => {
    editor?.chain().focus().toggleStrike().run()
  }, [editor])

  if (!editor) {
    return null
  }

  return (
    <div className="relative" ref={editorRef}>
      {/* Editor Content */}
      <EditorContent
        editor={editor}
        className="min-h-[2rem] prose prose-sm max-w-none focus-within:outline-none [&_u]:underline [&_u]:decoration-2 [&_u]:underline-offset-2 [&_u]:decoration-blue-500"
      />
      
      {/* Selection-based Toolbar - Show only when text is selected */}
      {showToolbar && (
        <div 
          className="absolute flex items-center space-x-1 bg-white border border-gray-300 rounded-lg shadow-xl px-3 py-2 z-50 transition-all duration-200"
          style={{
            top: `${toolbarPosition.top}px`,
            left: `${toolbarPosition.left}px`,
          }}
          data-toolbar="true"
          data-testid="selection-toolbar"
        >
          <Button
            variant={editor.isActive('bold') ? 'default' : 'ghost'}
            size="sm"
            className={`h-8 w-8 p-0 transition-all duration-200 ${
              editor.isActive('bold') 
                ? 'bg-blue-100 hover:bg-blue-200 text-blue-700 border border-blue-300' 
                : 'hover:bg-gray-100 text-gray-600'
            }`}
            onClick={toggleBold}
            onMouseDown={(e) => e.preventDefault()} // Prevent blur
            type="button"
            title="Bold (⌘B)"
          >
            <Bold className="h-4 w-4" />
          </Button>
          
          <Button
            variant={editor.isActive('italic') ? 'default' : 'ghost'}
            size="sm"
            className={`h-8 w-8 p-0 transition-all duration-200 ${
              editor.isActive('italic') 
                ? 'bg-blue-100 hover:bg-blue-200 text-blue-700 border border-blue-300' 
                : 'hover:bg-gray-100 text-gray-600'
            }`}
            onClick={toggleItalic}
            onMouseDown={(e) => e.preventDefault()} // Prevent blur
            type="button"
            title="Italic (⌘I)"
          >
            <Italic className="h-4 w-4" />
          </Button>
          
          <Button
            variant={editor.isActive('underline') ? 'default' : 'ghost'}
            size="sm"
            className={`h-8 w-8 p-0 transition-all duration-200 ${
              editor.isActive('underline') 
                ? 'bg-blue-100 hover:bg-blue-200 text-blue-700 border border-blue-300' 
                : 'hover:bg-gray-100 text-gray-600'
            }`}
            onClick={toggleUnderline}
            onMouseDown={(e) => e.preventDefault()} // Prevent blur
            type="button"
            title="Underline (⌘U)"
          >
            <UnderlineIcon className="h-4 w-4" />
          </Button>
          
          <Button
            variant={editor.isActive('strike') ? 'default' : 'ghost'}
            size="sm"
            className={`h-8 w-8 p-0 transition-all duration-200 ${
              editor.isActive('strike') 
                ? 'bg-blue-100 hover:bg-blue-200 text-blue-700 border border-blue-300' 
                : 'hover:bg-gray-100 text-gray-600'
            }`}
            onClick={toggleStrike}
            onMouseDown={(e) => e.preventDefault()} // Prevent blur
            type="button"
            title="Strikethrough (⌘⇧X)"
          >
            <Strikethrough className="h-4 w-4" />
          </Button>
        </div>
      )}
    </div>
  )
}
