// frontend-svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import "./app.css";
  import Login from "$lib/components/Login.svelte";
  import Sidebar from "$lib/components/Sidebar.svelte";
  import DocumentEditor from "$lib/components/DocumentEditor.svelte";
  import ReadOnlyDocumentViewer from "$lib/components/ReadOnlyDocumentViewer.svelte";
  import { authStore } from "$lib/stores/auth.svelte";

  // State
  let currentDocumentId = $state<number | null>(null);
  let showingSidebar = $state(true);
  let isReadOnly = $state(false);

  /**
   * ドキュメント選択処理を作成する関数
   */
  function createDocumentSelectHandler() {
    return (documentId: number, readOnly: boolean = false) => {
      currentDocumentId = documentId;
      isReadOnly = readOnly;
    };
  }

  /**
   * ドキュメント削除処理を作成する関数
   */
  function createDocumentDeleteHandler() {
    return (documentId: number) => {
      if (currentDocumentId === documentId) {
        currentDocumentId = null;
      }
    };
  }

  let handleDocumentSelect = $state(createDocumentSelectHandler());
  let handleDocumentDelete = $state(createDocumentDeleteHandler());

  /**
   * サイドバー切り替え
   */
  function toggleSidebar() {
    showingSidebar = !showingSidebar;
  }

  /**
   * ログアウト処理
   */
  async function handleLogout() {
    await authStore.logout();
  }

  // 初期化時に認証状態をチェック
  onMount(() => {
    authStore.checkAuth();
  });
</script>

<div class="h-screen w-screen overflow-hidden">
  {#if !authStore.user}
    <!-- ログイン画面 -->
    <Login />
  {:else}
    <!-- メインアプリケーション -->
    <div class="flex h-full">
      <!-- サイドバー -->
      <Sidebar
        bind:currentDocumentId
        bind:onDocumentSelect={handleDocumentSelect}
        bind:onDocumentDelete={handleDocumentDelete}
        bind:showingSidebar
      />

      <!-- メインコンテンツ -->
      <div class="flex-1 flex flex-col">
        <!-- ヘッダー -->
        <div
          class="border-b border-gray-200 p-4 flex items-center justify-between"
        >
          <div class="flex items-center space-x-4">
            <button
              onclick={toggleSidebar}
              class="p-2 hover:bg-gray-100 rounded-md transition-colors"
              title={showingSidebar ? "サイドバーを隠す" : "サイドバーを表示"}
            >
              <svg
                class="w-5 h-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M4 6h16M4 12h16M4 18h16"
                />
              </svg>
            </button>
            <h1 class="text-lg font-semibold">Simple Notion</h1>
            {#if isReadOnly}
              <span class="text-sm text-red-600 bg-red-50 px-2 py-1 rounded">
                読み取り専用
              </span>
            {/if}
          </div>

          <div class="flex items-center space-x-4">
            <span class="text-sm text-gray-600">
              {authStore.user.name}
            </span>
            <button
              onclick={handleLogout}
              class="px-4 py-2 text-sm text-white bg-red-500 hover:bg-red-600 rounded-md transition-colors"
            >
              ログアウト
            </button>
          </div>
        </div>

        <!-- ドキュメントエディター -->
        <div class="flex-1 overflow-auto">
          {#if currentDocumentId}
            {#if isReadOnly}
              <ReadOnlyDocumentViewer documentId={currentDocumentId} />
            {:else}
              <DocumentEditor documentId={currentDocumentId} />
            {/if}
          {:else}
            <div class="flex items-center justify-center h-full">
              <div class="text-center">
                <p class="text-gray-600 mb-2">ドキュメントを選択してください</p>
                <p class="text-sm text-gray-500">
                  左のサイドバーからドキュメントを選択するか、新しいドキュメントを作成してください
                </p>
              </div>
            </div>
          {/if}
        </div>
      </div>
    </div>
  {/if}
</div>

// frontend/src/App.tsx
import { useEffect, useState } from 'react'
import { useAuthStore } from '@/stores/auth'
import { Login } from '@/components/Login'
import { Sidebar } from '@/components/Sidebar'
import { DocumentEditor } from '@/components/DocumentEditor'
import { Button } from '@/components/ui/button'
import { Menu } from 'lucide-react'

function App() {
  const { user, checkAuth, logout } = useAuthStore()
  const [currentDocumentId, setCurrentDocumentId] = useState<number | null>(null)
  const [showingSidebar, setShowingSidebar] = useState(true)

  useEffect(() => {
    checkAuth()
  }, [checkAuth])

  useEffect(() => {
    // Listen for document deletion events
    const handleDocumentDeleted = (e: CustomEvent) => {
      if (e.detail.documentId === currentDocumentId) {
        setCurrentDocumentId(null)
      }
    }

    window.addEventListener('document-deleted', handleDocumentDeleted as EventListener)
    return () => window.removeEventListener('document-deleted', handleDocumentDeleted as EventListener)
  }, [currentDocumentId])

  if (!user) {
    return <Login />
  }

  return (
    <div className="flex h-screen bg-white">
      <Sidebar
        currentDocumentId={currentDocumentId}
        onDocumentSelect={setCurrentDocumentId}
        showingSidebar={showingSidebar}
        onToggleSidebar={() => setShowingSidebar(!showingSidebar)}
      />

      {/* Main Editor Area */}
      <div className="flex-1 flex flex-col">
        {/* Header */}
        <header className="h-12 border-b border-gray-200 flex items-center px-4">
          {!showingSidebar && (
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setShowingSidebar(true)}
              className="mr-2"
            >
              <Menu className="h-5 w-5" />
            </Button>
          )}

          <div className="flex-1"></div>

          <Button
            variant="ghost"
            onClick={logout}
            className="text-sm text-gray-600 hover:text-gray-800"
          >
            Logout
          </Button>
        </header>

        {/* Editor */}
        <main className="flex-1 overflow-hidden">
          {currentDocumentId ? (
            <DocumentEditor documentId={currentDocumentId} />
          ) : (
            <div className="flex items-center justify-center h-full text-gray-500">
              <div className="text-center">
                <svg
                  className="w-16 h-16 mx-auto mb-4 text-gray-300"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="1"
                    d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                  />
                </svg>
                <p className="text-lg">Select a document to start editing</p>
              </div>
            </div>
          )}
        </main>
      </div>
    </div>
  )
}

export default App
